\c postgres
DROP DATABASE foot;
DROP ROLE foot;
CREATE DATABASE foot;
CREATE ROLE foot LOGIN PASSWORD 'fifa';

\c foot;

GRANT SELECT , INSERT ON ALL TABLES IN SCHEMA public TO foot;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT , INSERT, UPDATE, DELETE ON TABLES TO foot;

GRANT CREATE ON SCHEMA public to foot;

